### ISSUE TITLE
How can I get train_data/gan_abc5k_t2comp_hrs_20k_sd15.jsonl data?

### ISSUE THREAD

**Issue by ugiugi0823** [CaraJ7/CoMat#10]
How can I get train_data/gan_abc5k_t2comp_hrs_20k_sd15.jsonl data?

**Comment by CaraJ7** [comment]
Hi @ugiugi0823. Please refer to [this](https://github.com/CaraJ7/CoMat#:~:text=fine%2Dtuned%20UNet.-,PYTHONPATH%3D%22%24(dirname%20%240)/..%22%3A%24PYTHONPATH,model%2Dpath%20stabilityai/stable%2Ddiffusion%2Dxl%2Dbase%2D1.0%20%5C%0A%2D%2Dmodel%2Dtype%20sdxl_unet,-Finally%20we%20start) script. The output jsonl file of this command is the `gan_abc5k_t2comp_hrs_20k_sd15.jsonl` data.
