### ISSUE TITLE
Training Error: ModuleNotFoundError: No module named 'TrainableSDPipeline'

### ISSUE THREAD

**Issue by rdcoder33** [CaraJ7/CoMat#11]
I am getting this error when running:

python3 tools/gan_gt_generate.py --prompt-path merged_data/comat-captions.txt --save-prompt-path train_data_sdxl/gan_gt_data.jsonl --unet-path <sdxl-512-optimized-model> --model-path stabilityai/stable-diffusion-xl-base-1.0 --model-type sdxl_unet

even though I have install `requirements.txt` file using pip

**Comment by rdcoder33** [comment]
I had to move gan_gt_generate.py from tools to root directory

**Comment by CaraJ7** [comment]
Hi @rdcoder33. You can add `PYTHONPATH="$(dirname $0)/..":$PYTHONPATH` before your python command like this: 
```bash
PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
python3 tools/gan_gt_generate.py --prompt-path merged_data/comat-captions.txt --save-prompt-path train_data_sdxl/gan_gt_data.jsonl --unet-path --model-path stabilityai/stable-diffusion-xl-base-1.0 --model-type sdxl_unet
```
so that you do not need to move the file.
