### ISSUE TITLE
Where is Ltxt? How does the Mixed Latent Strategy involved in training?

### ISSUE THREAD

**Issue by lrzjason** [CaraJ7/CoMat#13]
In Figure 4: Overview of CoMat. It has a loss call Ltxt. It involved a GT prompt and Text prompt. 

In the bottom description, it becomes Li2t which only involved the Text prompt.

Before section 5, The formula combines all losses which also doesn't include Ltxt.
![1723067244744](https://github.com/user-attachments/assets/0d0ba3b0-c27f-4bd7-a4fa-b00535331465)

I double checked in code, it only generated one image which doesn't using the 'Noisy GT'. 
![KL)5{_2I_0NVD)W{KGYA0PB](https://github.com/user-attachments/assets/d5964f08-25a2-4431-983a-1fc281671113)

And only once self.caption_model() to have call.

Does Mixed Latent Strategy was used in training at all?

**Comment by CaraJ7** [comment]
Hi @lrzjason, the current version does not include the mixed latent strategy. We will update the codebase recently. Please stay tuned!

**Comment by CaraJ7** [comment]
Thanks for pointing out the error in Fig. 4. In fact, the $\mathcal{L}\_{txt}$ in the figure should be $\mathcal{L}\_{i2t}$. $\mathcal{L}\_{i2t}$ involves both GT prompt and Text prompt.

**Comment by lrzjason** [comment]
@CaraJ7 Thanks for the reply.
