### ISSUE TITLE
Why not directly use resolution 1024 for SDXL?

### ISSUE THREAD

**Issue by kjzju** [CaraJ7/CoMat#9]
Thank you for your great work. I see that the current training of sdxl is based on resolution 512. Why not train it directly on resolution 1024? Are there any other considerations?

**Comment by CaraJ7** [comment]
Hi @kjzju. Please refer to the Appendix E.1 in our [paper](https://arxiv.org/pdf/2404.03653) for more details. In brief, training SDXL on resolution 1024 is very slow and we find that training on resolution 512 is of much higher efficiency, and the improvement can also transfer to resolution 1024.
